---
name: ollama
version: v0.6.6
base: core24
summary: Get up and running with large language models locally.
description: |
  Run Llama 2, Code Llama, and other models. Customize and create your own.
adopt-info: ollama
grade: stable
confinement: strict
license: MIT
platforms:
  amd64:
  arm64:

package-repositories:
  - type: apt
    formats: [deb]
    architectures: [amd64]
    path: /
    key-id: EB693B3035CD5710E231E123A4B469963BF863CC
    url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64
  - type: apt
    formats: [deb]
    architectures: [arm64]
    path: /
    key-id: EB693B3035CD5710E231E123A4B469963BF863CC
    url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/arm64

apps:
  ollama:
    command: bin/snap_launcher.sh
    plugs:
      - home
      - removable-media
      - network
      - network-bind
      - opengl # grants also CUDA based GPU access
  listener:
    command: bin/snap_launcher.sh serve
    daemon: simple
    install-mode: enable
    restart-condition: on-failure
    refresh-mode: restart
    plugs:
      - home
      - removable-media
      - network
      - network-bind
      - opengl
    environment:
      NVIDIA_DRIVER_CAPABILITIES: compute,utility

parts:
  launcher:
    plugin: dump
    source: ./snap/local
    organize:
      snap_launcher.sh: bin/snap_launcher.sh
  ollama:
    plugin: go
    source: https://github.com/ollama/ollama.git
    source-type: git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    # build packages (not staged) because ollama copies in cudnn, cublas etc
    build-packages:
      - git
      - gcc
      - cmake
      - sed
      - libcudnn9-cuda-12
      - libcublas-12-8
      - libcudnn9-dev-cuda-12
      - libcublas-dev-12-8
      - cuda-cudart-dev-12-8
      - cuda-driver-dev-12-8
      - tensorrt-libs
      - tensorrt-dev
      - cuda-toolkit-12-8
      - nvidia-cuda-dev
    build-snaps:
      - go/stable
    build-environment:
      - LD_LIBRARY_PATH: "/usr/lib/${CRAFT_ARCH_TRIPLET}/nvidia/:/usr/local/cuda-12.8/compat/${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
    override-pull: |
      craftctl default
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_committed_tag_ver="$(echo ${last_committed_tag} | sed 's/v//')"
      craftctl set version="$(git describe --tags | sed 's/v//')"

  libs:
    plugin: nil
    stage-packages:
      - libcudnn9-cuda-12
      - libcublas-12-8
      - cuda-libraries-12-8
    stage:
      - -usr/local
