name: Snap Build

on:
  pull_request:
    types: [opened, reopened]    
  workflow_dispatch:

jobs:
  build-amd64:
    runs-on: ubuntu-24.04
    steps:
    - uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
    - uses: snapcore/action-build@v1
      id: snapcraft
    - uses: actions/upload-artifact@v4
      with:
        name: snap
        path: ${{ steps.snapcraft.outputs.snap }}
        retention-days: 5
  build-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
    - uses: snapcore/action-build@v1
      id: snapcraft
    - uses: actions/upload-artifact@v4
      with:
        name: snap
        path: ${{ steps.snapcraft.outputs.snap }}
        retention-days: 5
